### PR TITLE
Support JSON 

### PR DESCRIPTION
**Pull request by smk762**
Adds support for json endpoints. 
Implemented via submodule in https://github.com/smk762/no_phish_nfts (back end calculates hmac and redirects)
Working example endpoint: https://nft.antispam.dragonhound.info/url_decode/68747470733a2f2f6a736f6e706c616365686f6c6465722e74797069636f64652e636f6d2f746f646f73 (leads to https://jsonplaceholder.typicode.com/todos)

### CODE REVIEW

**Comment by denschub** [comment]
Thanks for the PR!

Can you tell me a bit more about your use-case? From what I could tell, this looks less like an asset proxy, and more like a way to bypass CORS restrictions. While this isn't what I had in mind for this project, I also see no strong reason against this - but I wonder if a generic `--allow-all` flag that would just skip the mime type validation would make more sense.

**Comment by smk762** [comment]
Our use case is using the proxy to get [NFT metadata](https://medium.com/coinmonks/how-nft-metadata-works-a65ba7631842) in json format which may be hosted on domains which raise red flags in the browser.

Being crypto, scams and malicious content are a persistent concern, and though the json itself is safe, the domain it is hosted on (or the domain of asset urls within the json) might be [identified as malicious](https://developers.google.com/safe-browsing). 

Another upside is to avoid any "ip grabbers" collecting information on the users of our software when they attempt to load resources from external locations, which helps towards maintaining privacy.

To combat this, we've deployed a range of proxies and validators to filter out the bad and pass along the goods. Here's a link to the app if curious https://app.komodoplatform.com/ (tho the NFT features are still under development - a dev build is up at https://node.dragonhound.info:1001/)

**Comment by smk762** [comment]
> a generic --allow-all flag that would just skip the mime type validation would make more sense.

This would be a good option, as in testing it was clear that content type headers can be inconsistent. For example, https://raw.githubusercontent.com/KomodoPlatform/coins/master/coins is not tagged as `application/json`, its tagged as 
`text/plain; charset=utf-8`

**Comment by denschub** [comment]
Okay, yeah, I don't really care for your use-case, then (and neither do I care for anything cryptocurrency related). However, I agree that using `camo-rs` to proxy other resources is probably not a rare use-case, so I'd think an `--allow-any` option would be the best. An alternative way would be to make the list of mime-types configurable, but that'd be a lot of effort. I don't like the idea of explicitly allow-listing JSON now, as there is a never-ending list of mime-types that people could wish for.

Can you re-work this PR to add an `--allow-any` flag that just skips the entire mime-type check (and also allows empty/unset types)?

**Comment by smk762** [comment]
That's the beauty of open source - despite any disagreements about use we can still collaborate :)
I appreciate that you created this tool which helps us protect the privacy and security of our users, and I'm happy to contribute towards adding functionality that future users might find useful.

I did some testing earlier for an `--allow-all` option but still needs a bit of testing, I'll try and clean it up and push an update this weekend.

**Comment by denschub** [comment]
No rush.

This PR would need two new tests, `passes_missing_content_type_if_configured()` and `passes_arbitrary_content_type_if_configured()` that reverse the expectations from `rejects_missing_content_type()` and `rejects_invalid_content_type()` respectively. If you struggle with adding tests for the `--allow-all` pref, feel free to skip them. I'm happy to do that in a follow-up commit before releasing.

For reference, the current suite doesn't have the ability to work with non-"default" settings, so the tests in `tests/server.rs` need a bit of refactoring: each test should get its own settings from `get_test_settings()`, and then pass those settings into `run_valid_upstream_request()`/`run_test_server()`. That way, each test could mutate the settings individually.

**Comment by denschub** [comment]
@smk762 how's it going? :) I've received another request for this, and I'd like to cut a release soon. If you don't want to work on this, that's perfectly fine, and I'll take over implementing this!

**Comment by denschub** [comment]
Superseded by #110.

**Pull request closed without merging**
